"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.table = exports.presentTable = exports.pastTable = exports.Coordonate = exports.SChip = exports.SFrame = exports.SLine = exports.Symbol = void 0;
const symbol_1 = require("./components/symbol");
const s_line_1 = require("./components/s-line");
const s_chip_1 = require("./components/s-chip");
const s_frame_1 = require("./components/s-frame");
const coordonates_1 = require("./components/coordonates");
const tables_1 = require("./engine/tables");
const tables_2 = require("./engine/tables");
exports.Symbol = symbol_1.Symbol;
exports.SLine = s_line_1.SLine;
exports.SFrame = s_frame_1.SFrame;
exports.SChip = s_chip_1.SChip;
exports.Coordonate = coordonates_1.Coordonate;
exports.pastTable = tables_1.PastTable;
exports.presentTable = tables_1.PresentTable;
exports.table = tables_2.Table;
